### ISSUE TITLE
no such file or directory "blank_code.pkl"

### ISSUE THREAD

**Issue by Zhangjyhhh** [myc634/UltraLiDAR_nusc_waymo#3]
Hi I come back again! sorry to bother you again!
In training stage 1, when i run command, it show "no such file or directory "blank_code.pkl". but I see that  in eval step 0, it will generate blank_code.pkl, so i decide to run the command in eval step 0,but it still show "no such file or directory "blank_code.pkl". And i really don't  know how to solve this problem?

**Comment by myc634** [comment]
I uploaded a new version of code, please try this new one.

**Comment by Zhangjyhhh** [comment]
> I uploaded a new version of code, please try this new one.
thank you ,that's help a lot
