### ISSUE TITLE
getting error "FileNotFoundError: [Errno 2] No such file or directory: 'blank_code.pkl'", while running eval step 0 code.

### ISSUE THREAD

**Issue by Kafka2122** [myc634/UltraLiDAR_nusc_waymo#7]

**Comment by myc634** [comment]
Can you provide the config you run to help debug?

**Comment by Kafka2122** [comment]
I don't know somehow the error was resolved on restarting the docker container. I will try running the code again and see if the error comes back.

**Comment by Kafka2122** [comment]
I will close the issue for now
